create database Samay;
use Samay;
create table Countries(country_id bigint auto_increment primary key , country_name varchar(50), country_code varchar(50), currency_code varchar(50), continent_name varchar(50));
desc Countries;
create table TimeZone(timezone_id bigint auto_increment primary key, countr_id bigint ,foreign key(countr_id) references Countries(country_id),timezone_offset float);
desc TimeZone;
create table customer(cust_id bigint auto_increment primary key, cust_name Varchar(50), products_purchased varchar(100));
desc customer;
create table Events(event_id bigint auto_increment primary key, customer_id bigint ,foreign key(customer_id) references customer(cust_id),event_type varchar(50)); 
desc Events;
create table Employee(emp_id bigint auto_increment primary key, branch_name varchar(50), location varchar(50));
desc Employee;
insert into Countries(country_name,country_code,currency_code,continent_name)values("India",91,"INR","Asia");
insert into Countries(country_name,country_code,currency_code,continent_name)values("Canada",124,"CAD","NorthAmerica");
insert into Countries(country_name,country_code,currency_code,continent_name)values("Australia","61","AUD","Ocenia");
insert into Countries(country_name,country_code,currency_code,continent_name)values("Belgium","32","Euro","Europe");
insert into Countries(country_name,country_code,currency_code,continent_name)values("France","33","EUR","Europe");
insert into Countries(country_name,country_code,currency_code,continent_name)values("Belgium","32","Euro","Europe");
insert into Countries(country_name,country_code,currency_code,continent_name)values("Australia","61","AUD","Ocenia");
select * from countries;
select * from Countries;
insert into Countries(country_name,country_code,currency_code,continent_name)values("Canada",124,"CAD","NorthAmerica");
insert into Countries(country_name,country_code,currency_code,continent_name)values("India",91,"INR","Asia");
select * from Countries;
insert into TimeZone(timezone_offset)values(+04.30);
insert into TimeZone(timezone_offset)values(+01.00);
insert into TimeZone(timezone_offset)values(-05.00);
insert into TimeZone(timezone_offset)values(-04.00);
insert into TimeZone(timezone_offset)values(+05.30);
insert into TimeZone(timezone_offset)values(+05.30);
select * from TimeZone;
create table Customers(cust_name varchar(45), products_purc varchar(45));
desc Customers;
insert into Customers(cust_name,products_purc)values("Walmart","WaterPurifier");
insert into Customers(cust_name,products_purc)values("Amazon","book");
insert into Customers(cust_name,products_purc)values("UnitedHealthGroup","ParentalInsurance");
insert into Customers(cust_name,products_purc)values("CVSHealth","Covaccine");
insert into Customers(cust_name,products_purc)values("Amazon","book");
select * from Customers;
create table event(event_type varchar(45));
desc event;
insert into event(event_type)values('ChristmasParty');
insert into event(event_type)values('BirthdayParty');
insert into event(event_type)values('OffsitePlanningMeetings');
insert into event(event_type)values('BusinessMeeting');
insert into event(event_type)values('NewYearParty');
desc event;
select * from event;
create table employees(branch_name varchar(45), location varchar(45));
desc employees;
insert into employees(branch_name,location)values('FirstData','Chicago');
insert into employees(branch_name,location)values('Magneto','Pune');
insert into employees(branch_name,location)values('SLK','Germany');
insert into employees(branch_name,location)values('Sankey','Canada');
insert into employees(branch_name,location)values('TCS','Singapore');
select * from employees;
